// import 'raf/polyfill'
import { Inter } from 'next/font/google'

import { Provider } from '@mj/ui/providers'

import '@mj/tailwind/globals.css'

import { StylesProvider } from './styles-provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
      <body className={`${inter.className} scrollbar-thin scrollbar-thumb-amber-900 scrollbar-track-amber-100`}>
        <Provider>
          <StylesProvider>{children}</StylesProvider>
        </Provider>
      </body>
    </html>
  )
}
